// Code generated by MockGen. DO NOT EDIT.
// Source: principal.go
//
// Generated by this command:
//
//	mockgen -source=principal.go -destination=../mocks/principal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrincipal is a mock of Principal interface.
type MockPrincipal struct {
	ctrl     *gomock.Controller
	recorder *MockPrincipalMockRecorder
	isgomock struct{}
}

// MockPrincipalMockRecorder is the mock recorder for MockPrincipal.
type MockPrincipalMockRecorder struct {
	mock *MockPrincipal
}

// NewMockPrincipal creates a new mock instance.
func NewMockPrincipal(ctrl *gomock.Controller) *MockPrincipal {
	mock := &MockPrincipal{ctrl: ctrl}
	mock.recorder = &MockPrincipalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrincipal) EXPECT() *MockPrincipalMockRecorder {
	return m.recorder
}

// GetIss mocks base method.
func (m *MockPrincipal) GetIss() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIss")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIss indicates an expected call of GetIss.
func (mr *MockPrincipalMockRecorder) GetIss() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIss", reflect.TypeOf((*MockPrincipal)(nil).GetIss))
}

// GetScopes mocks base method.
func (m *MockPrincipal) GetScopes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScopes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetScopes indicates an expected call of GetScopes.
func (mr *MockPrincipalMockRecorder) GetScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopes", reflect.TypeOf((*MockPrincipal)(nil).GetScopes))
}

// GetSub mocks base method.
func (m *MockPrincipal) GetSub() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSub")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSub indicates an expected call of GetSub.
func (mr *MockPrincipalMockRecorder) GetSub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSub", reflect.TypeOf((*MockPrincipal)(nil).GetSub))
}

// HasScope mocks base method.
func (m *MockPrincipal) HasScope(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasScope", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasScope indicates an expected call of HasScope.
func (mr *MockPrincipalMockRecorder) HasScope(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasScope", reflect.TypeOf((*MockPrincipal)(nil).HasScope), arg0)
}

// MatchesOwner mocks base method.
func (m *MockPrincipal) MatchesOwner(iss, sub string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesOwner", iss, sub)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchesOwner indicates an expected call of MatchesOwner.
func (mr *MockPrincipalMockRecorder) MatchesOwner(iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesOwner", reflect.TypeOf((*MockPrincipal)(nil).MatchesOwner), iss, sub)
}
