// Code generated by MockGen. DO NOT EDIT.
// Source: principal.go
//
// Generated by this command:
//
//	mockgen -source=principal.go -destination=../mocks/principal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	config "homelab-dashboard/internal/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrincipal is a mock of Principal interface.
type MockPrincipal struct {
	ctrl     *gomock.Controller
	recorder *MockPrincipalMockRecorder
	isgomock struct{}
}

// MockPrincipalMockRecorder is the mock recorder for MockPrincipal.
type MockPrincipalMockRecorder struct {
	mock *MockPrincipal
}

// NewMockPrincipal creates a new mock instance.
func NewMockPrincipal(ctrl *gomock.Controller) *MockPrincipal {
	mock := &MockPrincipal{ctrl: ctrl}
	mock.recorder = &MockPrincipalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrincipal) EXPECT() *MockPrincipalMockRecorder {
	return m.recorder
}

// GetDisplayName mocks base method.
func (m *MockPrincipal) GetDisplayName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisplayName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDisplayName indicates an expected call of GetDisplayName.
func (mr *MockPrincipalMockRecorder) GetDisplayName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisplayName", reflect.TypeOf((*MockPrincipal)(nil).GetDisplayName))
}

// GetEmail mocks base method.
func (m *MockPrincipal) GetEmail() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmail")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEmail indicates an expected call of GetEmail.
func (mr *MockPrincipalMockRecorder) GetEmail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmail", reflect.TypeOf((*MockPrincipal)(nil).GetEmail))
}

// GetGroups mocks base method.
func (m *MockPrincipal) GetGroups() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockPrincipalMockRecorder) GetGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockPrincipal)(nil).GetGroups))
}

// GetIss mocks base method.
func (m *MockPrincipal) GetIss() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIss")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIss indicates an expected call of GetIss.
func (mr *MockPrincipalMockRecorder) GetIss() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIss", reflect.TypeOf((*MockPrincipal)(nil).GetIss))
}

// GetScopes mocks base method.
func (m *MockPrincipal) GetScopes(cfg *config.Config) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScopes", cfg)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetScopes indicates an expected call of GetScopes.
func (mr *MockPrincipalMockRecorder) GetScopes(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopes", reflect.TypeOf((*MockPrincipal)(nil).GetScopes), cfg)
}

// GetSub mocks base method.
func (m *MockPrincipal) GetSub() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSub")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSub indicates an expected call of GetSub.
func (mr *MockPrincipalMockRecorder) GetSub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSub", reflect.TypeOf((*MockPrincipal)(nil).GetSub))
}

// GetUsername mocks base method.
func (m *MockPrincipal) GetUsername() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsername")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUsername indicates an expected call of GetUsername.
func (mr *MockPrincipalMockRecorder) GetUsername() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsername", reflect.TypeOf((*MockPrincipal)(nil).GetUsername))
}

// HasScope mocks base method.
func (m *MockPrincipal) HasScope(cfg *config.Config, scope string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasScope", cfg, scope)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasScope indicates an expected call of HasScope.
func (mr *MockPrincipalMockRecorder) HasScope(cfg, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasScope", reflect.TypeOf((*MockPrincipal)(nil).HasScope), cfg, scope)
}

// MatchesOwner mocks base method.
func (m *MockPrincipal) MatchesOwner(iss, sub string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesOwner", iss, sub)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchesOwner indicates an expected call of MatchesOwner.
func (mr *MockPrincipalMockRecorder) MatchesOwner(iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesOwner", reflect.TypeOf((*MockPrincipal)(nil).MatchesOwner), iss, sub)
}
