// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=../mocks/storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "homelab-dashboard/internal/models"
	slog "log/slog"
	reflect "reflect"
	time "time"

	uasurfer "github.com/avct/uasurfer"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageProvider is a mock of StorageProvider interface.
type MockStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStorageProviderMockRecorder
	isgomock struct{}
}

// MockStorageProviderMockRecorder is the mock recorder for MockStorageProvider.
type MockStorageProviderMockRecorder struct {
	mock *MockStorageProvider
}

// NewMockStorageProvider creates a new mock instance.
func NewMockStorageProvider(ctrl *gomock.Controller) *MockStorageProvider {
	mock := &MockStorageProvider{ctrl: ctrl}
	mock.recorder = &MockStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageProvider) EXPECT() *MockStorageProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorageProvider) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStorageProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorageProvider)(nil).Close))
}

// CreateCertificateRequest mocks base method.
func (m *MockStorageProvider) CreateCertificateRequest(ctx context.Context, sub, iss, commonName, status, message string, dnsNames, organizationalUnits []string, validityDays int) (*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCertificateRequest", ctx, sub, iss, commonName, status, message, dnsNames, organizationalUnits, validityDays)
	ret0, _ := ret[0].(*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCertificateRequest indicates an expected call of CreateCertificateRequest.
func (mr *MockStorageProviderMockRecorder) CreateCertificateRequest(ctx, sub, iss, commonName, status, message, dnsNames, organizationalUnits, validityDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCertificateRequest", reflect.TypeOf((*MockStorageProvider)(nil).CreateCertificateRequest), ctx, sub, iss, commonName, status, message, dnsNames, organizationalUnits, validityDays)
}

// CreateServiceAccount mocks base method.
func (m *MockStorageProvider) CreateServiceAccount(ctx context.Context, user *models.ServiceAccount) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", ctx, user)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockStorageProviderMockRecorder) CreateServiceAccount(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).CreateServiceAccount), ctx, user)
}

// CreateUser mocks base method.
func (m *MockStorageProvider) CreateUser(ctx context.Context, sub, iss, username, displayName, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, sub, iss, username, displayName, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageProviderMockRecorder) CreateUser(ctx, sub, iss, username, displayName, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorageProvider)(nil).CreateUser), ctx, sub, iss, username, displayName, email)
}

// DeleteServiceAccount mocks base method.
func (m *MockStorageProvider) DeleteServiceAccount(ctx context.Context, iss, sub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", ctx, iss, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockStorageProviderMockRecorder) DeleteServiceAccount(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).DeleteServiceAccount), ctx, iss, sub)
}

// DisableServiceAccount mocks base method.
func (m *MockStorageProvider) DisableServiceAccount(ctx context.Context, iss, sub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableServiceAccount", ctx, iss, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableServiceAccount indicates an expected call of DisableServiceAccount.
func (mr *MockStorageProviderMockRecorder) DisableServiceAccount(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).DisableServiceAccount), ctx, iss, sub)
}

// EnableServiceAccount mocks base method.
func (m *MockStorageProvider) EnableServiceAccount(ctx context.Context, iss, sub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableServiceAccount", ctx, iss, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableServiceAccount indicates an expected call of EnableServiceAccount.
func (mr *MockStorageProviderMockRecorder) EnableServiceAccount(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).EnableServiceAccount), ctx, iss, sub)
}

// EnsureSystemUser mocks base method.
func (m *MockStorageProvider) EnsureSystemUser(ctx context.Context, logger *slog.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSystemUser", ctx, logger)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureSystemUser indicates an expected call of EnsureSystemUser.
func (mr *MockStorageProviderMockRecorder) EnsureSystemUser(ctx, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSystemUser", reflect.TypeOf((*MockStorageProvider)(nil).EnsureSystemUser), ctx, logger)
}

// GetApprovedCertificateRequests mocks base method.
func (m *MockStorageProvider) GetApprovedCertificateRequests(ctx context.Context) ([]*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedCertificateRequests", ctx)
	ret0, _ := ret[0].([]*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovedCertificateRequests indicates an expected call of GetApprovedCertificateRequests.
func (mr *MockStorageProviderMockRecorder) GetApprovedCertificateRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedCertificateRequests", reflect.TypeOf((*MockStorageProvider)(nil).GetApprovedCertificateRequests), ctx)
}

// GetCertificateDownloadAuditLogByID mocks base method.
func (m *MockStorageProvider) GetCertificateDownloadAuditLogByID(ctx context.Context, id int) (*models.CertificateDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateDownloadAuditLogByID", ctx, id)
	ret0, _ := ret[0].(*models.CertificateDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificateDownloadAuditLogByID indicates an expected call of GetCertificateDownloadAuditLogByID.
func (mr *MockStorageProviderMockRecorder) GetCertificateDownloadAuditLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateDownloadAuditLogByID", reflect.TypeOf((*MockStorageProvider)(nil).GetCertificateDownloadAuditLogByID), ctx, id)
}

// GetCertificateRequestByID mocks base method.
func (m *MockStorageProvider) GetCertificateRequestByID(ctx context.Context, id int) (*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateRequestByID", ctx, id)
	ret0, _ := ret[0].(*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificateRequestByID indicates an expected call of GetCertificateRequestByID.
func (mr *MockStorageProviderMockRecorder) GetCertificateRequestByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateRequestByID", reflect.TypeOf((*MockStorageProvider)(nil).GetCertificateRequestByID), ctx, id)
}

// GetCertificateRequests mocks base method.
func (m *MockStorageProvider) GetCertificateRequests(ctx context.Context) ([]*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateRequests", ctx)
	ret0, _ := ret[0].([]*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificateRequests indicates an expected call of GetCertificateRequests.
func (mr *MockStorageProviderMockRecorder) GetCertificateRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateRequests", reflect.TypeOf((*MockStorageProvider)(nil).GetCertificateRequests), ctx)
}

// GetCertificateRequestsByUser mocks base method.
func (m *MockStorageProvider) GetCertificateRequestsByUser(ctx context.Context, sub, iss string) ([]*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateRequestsByUser", ctx, sub, iss)
	ret0, _ := ret[0].([]*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificateRequestsByUser indicates an expected call of GetCertificateRequestsByUser.
func (mr *MockStorageProviderMockRecorder) GetCertificateRequestsByUser(ctx, sub, iss any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateRequestsByUser", reflect.TypeOf((*MockStorageProvider)(nil).GetCertificateRequestsByUser), ctx, sub, iss)
}

// GetCertificateRequestsPaginated mocks base method.
func (m *MockStorageProvider) GetCertificateRequestsPaginated(ctx context.Context, params models.PaginationParams) (*models.PaginatedCertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificateRequestsPaginated", ctx, params)
	ret0, _ := ret[0].(*models.PaginatedCertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificateRequestsPaginated indicates an expected call of GetCertificateRequestsPaginated.
func (mr *MockStorageProviderMockRecorder) GetCertificateRequestsPaginated(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificateRequestsPaginated", reflect.TypeOf((*MockStorageProvider)(nil).GetCertificateRequestsPaginated), ctx, params)
}

// GetPendingCertificateRequests mocks base method.
func (m *MockStorageProvider) GetPendingCertificateRequests(ctx context.Context) ([]*models.CertificateRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCertificateRequests", ctx)
	ret0, _ := ret[0].([]*models.CertificateRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCertificateRequests indicates an expected call of GetPendingCertificateRequests.
func (mr *MockStorageProviderMockRecorder) GetPendingCertificateRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCertificateRequests", reflect.TypeOf((*MockStorageProvider)(nil).GetPendingCertificateRequests), ctx)
}

// GetPool mocks base method.
func (m *MockStorageProvider) GetPool() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetPool indicates an expected call of GetPool.
func (mr *MockStorageProviderMockRecorder) GetPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockStorageProvider)(nil).GetPool))
}

// GetRecentCertificateDownloadLogs mocks base method.
func (m *MockStorageProvider) GetRecentCertificateDownloadLogs(ctx context.Context, limit int) ([]models.CertificateDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentCertificateDownloadLogs", ctx, limit)
	ret0, _ := ret[0].([]models.CertificateDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentCertificateDownloadLogs indicates an expected call of GetRecentCertificateDownloadLogs.
func (mr *MockStorageProviderMockRecorder) GetRecentCertificateDownloadLogs(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentCertificateDownloadLogs", reflect.TypeOf((*MockStorageProvider)(nil).GetRecentCertificateDownloadLogs), ctx, limit)
}

// GetServiceAccountByID mocks base method.
func (m *MockStorageProvider) GetServiceAccountByID(ctx context.Context, iss, sub string) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountByID", ctx, iss, sub)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountByID indicates an expected call of GetServiceAccountByID.
func (mr *MockStorageProviderMockRecorder) GetServiceAccountByID(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountByID", reflect.TypeOf((*MockStorageProvider)(nil).GetServiceAccountByID), ctx, iss, sub)
}

// GetServiceAccountByLookupId mocks base method.
func (m *MockStorageProvider) GetServiceAccountByLookupId(ctx context.Context, tokenHash string) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountByLookupId", ctx, tokenHash)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountByLookupId indicates an expected call of GetServiceAccountByLookupId.
func (mr *MockStorageProviderMockRecorder) GetServiceAccountByLookupId(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountByLookupId", reflect.TypeOf((*MockStorageProvider)(nil).GetServiceAccountByLookupId), ctx, tokenHash)
}

// GetServiceAccountsByCreator mocks base method.
func (m *MockStorageProvider) GetServiceAccountsByCreator(ctx context.Context, iss, sub string) ([]*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountsByCreator", ctx, iss, sub)
	ret0, _ := ret[0].([]*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountsByCreator indicates an expected call of GetServiceAccountsByCreator.
func (mr *MockStorageProviderMockRecorder) GetServiceAccountsByCreator(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountsByCreator", reflect.TypeOf((*MockStorageProvider)(nil).GetServiceAccountsByCreator), ctx, iss, sub)
}

// GetSystemUser mocks base method.
func (m *MockStorageProvider) GetSystemUser(ctx context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemUser", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSystemUser indicates an expected call of GetSystemUser.
func (mr *MockStorageProviderMockRecorder) GetSystemUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemUser", reflect.TypeOf((*MockStorageProvider)(nil).GetSystemUser), ctx)
}

// GetUserByID mocks base method.
func (m *MockStorageProvider) GetUserByID(ctx context.Context, iss, sub string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, iss, sub)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStorageProviderMockRecorder) GetUserByID(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStorageProvider)(nil).GetUserByID), ctx, iss, sub)
}

// InsertAuditLogCertificateDownload mocks base method.
func (m *MockStorageProvider) InsertAuditLogCertificateDownload(ctx context.Context, certId int, sub, iss, ipAddress, rawUserAgent string, userAgent uasurfer.UserAgent) (*models.CertificateDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuditLogCertificateDownload", ctx, certId, sub, iss, ipAddress, rawUserAgent, userAgent)
	ret0, _ := ret[0].(*models.CertificateDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAuditLogCertificateDownload indicates an expected call of InsertAuditLogCertificateDownload.
func (mr *MockStorageProviderMockRecorder) InsertAuditLogCertificateDownload(ctx, certId, sub, iss, ipAddress, rawUserAgent, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuditLogCertificateDownload", reflect.TypeOf((*MockStorageProvider)(nil).InsertAuditLogCertificateDownload), ctx, certId, sub, iss, ipAddress, rawUserAgent, userAgent)
}

// PauseServiceAccount mocks base method.
func (m *MockStorageProvider) PauseServiceAccount(ctx context.Context, iss, sub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseServiceAccount", ctx, iss, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseServiceAccount indicates an expected call of PauseServiceAccount.
func (mr *MockStorageProviderMockRecorder) PauseServiceAccount(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).PauseServiceAccount), ctx, iss, sub)
}

// Ping mocks base method.
func (m *MockStorageProvider) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageProviderMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorageProvider)(nil).Ping), ctx)
}

// RunMigrations mocks base method.
func (m *MockStorageProvider) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockStorageProviderMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockStorageProvider)(nil).RunMigrations), ctx)
}

// UnpauseServiceAccount mocks base method.
func (m *MockStorageProvider) UnpauseServiceAccount(ctx context.Context, iss, sub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpauseServiceAccount", ctx, iss, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpauseServiceAccount indicates an expected call of UnpauseServiceAccount.
func (mr *MockStorageProviderMockRecorder) UnpauseServiceAccount(ctx, iss, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpauseServiceAccount", reflect.TypeOf((*MockStorageProvider)(nil).UnpauseServiceAccount), ctx, iss, sub)
}

// UpdateCertificateK8sMetadata mocks base method.
func (m *MockStorageProvider) UpdateCertificateK8sMetadata(ctx context.Context, requestID int, certName, namespace, secretName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCertificateK8sMetadata", ctx, requestID, certName, namespace, secretName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCertificateK8sMetadata indicates an expected call of UpdateCertificateK8sMetadata.
func (mr *MockStorageProviderMockRecorder) UpdateCertificateK8sMetadata(ctx, requestID, certName, namespace, secretName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCertificateK8sMetadata", reflect.TypeOf((*MockStorageProvider)(nil).UpdateCertificateK8sMetadata), ctx, requestID, certName, namespace, secretName)
}

// UpdateCertificateRequestIssued mocks base method.
func (m *MockStorageProvider) UpdateCertificateRequestIssued(ctx context.Context, requestID int, certPEM, serialNumber string, issuedAt, expiresAt time.Time, systemUserIss, systemUserSub string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCertificateRequestIssued", ctx, requestID, certPEM, serialNumber, issuedAt, expiresAt, systemUserIss, systemUserSub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCertificateRequestIssued indicates an expected call of UpdateCertificateRequestIssued.
func (mr *MockStorageProviderMockRecorder) UpdateCertificateRequestIssued(ctx, requestID, certPEM, serialNumber, issuedAt, expiresAt, systemUserIss, systemUserSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCertificateRequestIssued", reflect.TypeOf((*MockStorageProvider)(nil).UpdateCertificateRequestIssued), ctx, requestID, certPEM, serialNumber, issuedAt, expiresAt, systemUserIss, systemUserSub)
}

// UpdateCertificateRequestStatus mocks base method.
func (m *MockStorageProvider) UpdateCertificateRequestStatus(ctx context.Context, requestId int, newStatus models.CertificateRequestStatus, reviewerIss, reviewerSub, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCertificateRequestStatus", ctx, requestId, newStatus, reviewerIss, reviewerSub, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCertificateRequestStatus indicates an expected call of UpdateCertificateRequestStatus.
func (mr *MockStorageProviderMockRecorder) UpdateCertificateRequestStatus(ctx, requestId, newStatus, reviewerIss, reviewerSub, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCertificateRequestStatus", reflect.TypeOf((*MockStorageProvider)(nil).UpdateCertificateRequestStatus), ctx, requestId, newStatus, reviewerIss, reviewerSub, notes)
}

// UpsertUser mocks base method.
func (m *MockStorageProvider) UpsertUser(ctx context.Context, sub, iss, username, displayName, email string, groups []string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, sub, iss, username, displayName, email, groups)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockStorageProviderMockRecorder) UpsertUser(ctx, sub, iss, username, displayName, email, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockStorageProvider)(nil).UpsertUser), ctx, sub, iss, username, displayName, email, groups)
}
