version: 2
updates:
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
