/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SettingsServiceAccountsRouteImport } from './routes/settings/service-accounts'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as SettingsFirewallIndexRouteImport } from './routes/settings/firewall/index'
import { Route as SettingsCertsIndexRouteImport } from './routes/settings/certs/index'
import { Route as SettingsFirewallAddRouteImport } from './routes/settings/firewall/add'
import { Route as SettingsCertsSettingsRouteImport } from './routes/settings/certs/settings'
import { Route as SettingsCertsRequestsRouteImport } from './routes/settings/certs/requests'
import { Route as SettingsCertsAdminRequestsRouteImport } from './routes/settings/certs/admin/requests'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsServiceAccountsRoute = SettingsServiceAccountsRouteImport.update({
  id: '/service-accounts',
  path: '/service-accounts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFirewallIndexRoute = SettingsFirewallIndexRouteImport.update({
  id: '/firewall/',
  path: '/firewall/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCertsIndexRoute = SettingsCertsIndexRouteImport.update({
  id: '/certs/',
  path: '/certs/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFirewallAddRoute = SettingsFirewallAddRouteImport.update({
  id: '/firewall/add',
  path: '/firewall/add',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCertsSettingsRoute = SettingsCertsSettingsRouteImport.update({
  id: '/certs/settings',
  path: '/certs/settings',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCertsRequestsRoute = SettingsCertsRequestsRouteImport.update({
  id: '/certs/requests',
  path: '/certs/requests',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCertsAdminRequestsRoute =
  SettingsCertsAdminRequestsRouteImport.update({
    id: '/certs/admin/requests',
    path: '/certs/admin/requests',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/blog/': typeof BlogIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/certs/requests': typeof SettingsCertsRequestsRoute
  '/settings/certs/settings': typeof SettingsCertsSettingsRoute
  '/settings/firewall/add': typeof SettingsFirewallAddRoute
  '/settings/certs/': typeof SettingsCertsIndexRoute
  '/settings/firewall/': typeof SettingsFirewallIndexRoute
  '/settings/certs/admin/requests': typeof SettingsCertsAdminRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/blog': typeof BlogIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/certs/requests': typeof SettingsCertsRequestsRoute
  '/settings/certs/settings': typeof SettingsCertsSettingsRoute
  '/settings/firewall/add': typeof SettingsFirewallAddRoute
  '/settings/certs': typeof SettingsCertsIndexRoute
  '/settings/firewall': typeof SettingsFirewallIndexRoute
  '/settings/certs/admin/requests': typeof SettingsCertsAdminRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/blog/': typeof BlogIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/certs/requests': typeof SettingsCertsRequestsRoute
  '/settings/certs/settings': typeof SettingsCertsSettingsRoute
  '/settings/firewall/add': typeof SettingsFirewallAddRoute
  '/settings/certs/': typeof SettingsCertsIndexRoute
  '/settings/firewall/': typeof SettingsFirewallIndexRoute
  '/settings/certs/admin/requests': typeof SettingsCertsAdminRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/about'
    | '/error'
    | '/blog/$slug'
    | '/settings/profile'
    | '/settings/service-accounts'
    | '/blog/'
    | '/settings/'
    | '/settings/certs/requests'
    | '/settings/certs/settings'
    | '/settings/firewall/add'
    | '/settings/certs/'
    | '/settings/firewall/'
    | '/settings/certs/admin/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/error'
    | '/blog/$slug'
    | '/settings/profile'
    | '/settings/service-accounts'
    | '/blog'
    | '/settings'
    | '/settings/certs/requests'
    | '/settings/certs/settings'
    | '/settings/firewall/add'
    | '/settings/certs'
    | '/settings/firewall'
    | '/settings/certs/admin/requests'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/about'
    | '/error'
    | '/blog/$slug'
    | '/settings/profile'
    | '/settings/service-accounts'
    | '/blog/'
    | '/settings/'
    | '/settings/certs/requests'
    | '/settings/certs/settings'
    | '/settings/firewall/add'
    | '/settings/certs/'
    | '/settings/firewall/'
    | '/settings/certs/admin/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ErrorRoute: typeof ErrorRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/service-accounts': {
      id: '/settings/service-accounts'
      path: '/service-accounts'
      fullPath: '/settings/service-accounts'
      preLoaderRoute: typeof SettingsServiceAccountsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/firewall/': {
      id: '/settings/firewall/'
      path: '/firewall'
      fullPath: '/settings/firewall/'
      preLoaderRoute: typeof SettingsFirewallIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/certs/': {
      id: '/settings/certs/'
      path: '/certs'
      fullPath: '/settings/certs/'
      preLoaderRoute: typeof SettingsCertsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/firewall/add': {
      id: '/settings/firewall/add'
      path: '/firewall/add'
      fullPath: '/settings/firewall/add'
      preLoaderRoute: typeof SettingsFirewallAddRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/certs/settings': {
      id: '/settings/certs/settings'
      path: '/certs/settings'
      fullPath: '/settings/certs/settings'
      preLoaderRoute: typeof SettingsCertsSettingsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/certs/requests': {
      id: '/settings/certs/requests'
      path: '/certs/requests'
      fullPath: '/settings/certs/requests'
      preLoaderRoute: typeof SettingsCertsRequestsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/certs/admin/requests': {
      id: '/settings/certs/admin/requests'
      path: '/certs/admin/requests'
      fullPath: '/settings/certs/admin/requests'
      preLoaderRoute: typeof SettingsCertsAdminRequestsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsServiceAccountsRoute: typeof SettingsServiceAccountsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsCertsRequestsRoute: typeof SettingsCertsRequestsRoute
  SettingsCertsSettingsRoute: typeof SettingsCertsSettingsRoute
  SettingsFirewallAddRoute: typeof SettingsFirewallAddRoute
  SettingsCertsIndexRoute: typeof SettingsCertsIndexRoute
  SettingsFirewallIndexRoute: typeof SettingsFirewallIndexRoute
  SettingsCertsAdminRequestsRoute: typeof SettingsCertsAdminRequestsRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsServiceAccountsRoute: SettingsServiceAccountsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsCertsRequestsRoute: SettingsCertsRequestsRoute,
  SettingsCertsSettingsRoute: SettingsCertsSettingsRoute,
  SettingsFirewallAddRoute: SettingsFirewallAddRoute,
  SettingsCertsIndexRoute: SettingsCertsIndexRoute,
  SettingsFirewallIndexRoute: SettingsFirewallIndexRoute,
  SettingsCertsAdminRequestsRoute: SettingsCertsAdminRequestsRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ErrorRoute: ErrorRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
